In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv


In [2]:
import pandas as pd
train_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
train_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
test_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [4]:
train_df['SalePrice'].mean()

180921.19589041095

In [5]:
test_df['SalePrice']=pd.Series([train_df['SalePrice'].mean()]*len(train_df))
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition     SalePrice  
0         6   2010        WD         Normal  180921.19589  
1         6   2010        WD         Normal  180921.19589  
2         3   2010        WD         Normal  180921.19589  
3         6   2010        WD         Normal  180921.19589  
4         1   2010        WD         Normal  180921.19589  
...     ...    ...       ...            ...           ...  
1454      6   2006        WD         Normal  180921.19589  
1455      4   2006        WD        Abnorml  180921.19589  
1456      9   2006        WD        Abnorml  180921.19589  
1457      7   2006        WD         Normal  180921.19589  
1458     11   2006        WD         Normal  180921.19589  

[1459 rows x 81 columns]

In [6]:
test_df[['Id', 'SalePrice']].to_csv('average_prediction.csv' , index = False)

In [17]:
from copy import deepcopy

train_df_sub =deepcopy(train_df[['LotFrontage','LotArea','SalePrice']])

train_df_sub

LotFrontage  LotArea  SalePrice
0            65.0     8450     208500
1            80.0     9600     181500
2            68.0    11250     223500
3            60.0     9550     140000
4            84.0    14260     250000
...           ...      ...        ...
1455         62.0     7917     175000
1456         85.0    13175     210000
1457         66.0     9042     266500
1458         68.0     9717     142125
1459         75.0     9937     147500

[1460 rows x 3 columns]

In [18]:
train_df_sub = train_df_sub.fillna(train_df_sub.mean())
train_df_sub

LotFrontage  LotArea  SalePrice
0            65.0     8450     208500
1            80.0     9600     181500
2            68.0    11250     223500
3            60.0     9550     140000
4            84.0    14260     250000
...           ...      ...        ...
1455         62.0     7917     175000
1456         85.0    13175     210000
1457         66.0     9042     266500
1458         68.0     9717     142125
1459         75.0     9937     147500

[1460 rows x 3 columns]

In [19]:
x_train, y_train = train_df_sub.to_numpy()[:,:-1], train_df_sub.to_numpy()[:,-1]
y_train

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(x_train, y_train)
lr

LinearRegression()

In [21]:
lr.coef_

array([1011.21616339,    1.41542572])

In [22]:
lr.intercept_

95199.75677006671

In [24]:
test_df_sub =deepcopy(test_df[['LotFrontage','LotArea']])

test_df_sub

LotFrontage  LotArea
0            80.0    11622
1            81.0    14267
2            74.0    13830
3            78.0     9978
4            43.0     5005
...           ...      ...
1454         21.0     1936
1455         21.0     1894
1456        160.0    20000
1457         62.0    10441
1458         74.0     9627

[1459 rows x 2 columns]

In [25]:
test_df_sub = test_df_sub.fillna(test_df_sub.mean())
test_df_sub

LotFrontage  LotArea
0            80.0    11622
1            81.0    14267
2            74.0    13830
3            78.0     9978
4            43.0     5005
...           ...      ...
1454         21.0     1936
1455         21.0     1894
1456        160.0    20000
1457         62.0    10441
1458         74.0     9627

[1459 rows x 2 columns]

In [26]:
x_test = test_df_sub.to_numpy()
x_test

array([[   80., 11622.],
       [   81., 14267.],
       [   74., 13830.],
       ...,
       [  160., 20000.],
       [   62., 10441.],
       [   74.,  9627.]])

In [27]:
test_df['SalePrice'] = lr.predict(x_test)
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition      SalePrice  
0         6   2010        WD         Normal  192547.127574  
1         6   2010        WD         Normal  197302.144770  
2         3   2010        WD         Normal  189605.090586  
3         6   2010        WD         Normal  188197.735361  
4         1   2010        WD         Normal  145766.257531  
...     ...    ...       ...            ...            ...  
1454      6   2006        WD         Normal  119175.560398  
1455      4   2006        WD        Abnorml  119116.112517  
1456      9   2006        WD        Abnorml  285302.857338  
1457      7   2006        WD         Normal  172673.618856  
1458     11   2006        WD         Normal  183656.056280  

[1459 rows x 81 columns]

In [29]:
test_df[['Id', 'SalePrice']].to_csv('linear_predictionn.csv' , index = False)